const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const authGate=$('#authGate'),site=$('#site'),authMessage=$('#authMessage');
function showSite(){authGate.classList.add('hidden');site.classList.remove('hidden');document.body.classList.remove('authing');setTimeout(()=>$$('.reveal').forEach(el=>observer.observe(el)),50)}
function showAuth(){authGate.classList.remove('hidden');site.classList.add('hidden')}
const saved=localStorage.getItem('royalstayUser'); if(saved) showSite(); else showAuth();
$$('[data-auth-tab]').forEach(btn=>btn.addEventListener('click',()=>{ $$('[data-auth-tab]').forEach(x=>x.classList.remove('active'));btn.classList.add('active');const signup=btn.dataset.authTab==='signup';$('#signupForm').classList.toggle('active-form',signup);$('#loginForm').classList.toggle('active-form',!signup);authMessage.textContent='';}));
$('#signupForm').addEventListener('submit',e=>{e.preventDefault();const user={name:$('#signupName').value,email:$('#signupEmail').value,password:$('#signupPassword').value};localStorage.setItem('royalstayUser',JSON.stringify(user));showToast('Account created — welcome to RoyalStay');showSite()});
$('#loginForm').addEventListener('submit',e=>{e.preventDefault();const user=JSON.parse(localStorage.getItem('royalstayUser')||'null');if(!user||user.email!==$('#loginEmail').value||user.password!==$('#loginPassword').value){authMessage.textContent='No matching demo account. Create an account first or use the same details you signed up with.';return}showSite()});
$('#logoutBtn').addEventListener('click',()=>{localStorage.removeItem('royalstayUser');showAuth();window.scrollTo(0,0)});
const menuBtn=$('#menuBtn'),nav=$('#nav');menuBtn.addEventListener('click',()=>nav.classList.toggle('open'));$$('.nav a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));
$('#themeToggle').addEventListener('click',()=>{document.body.classList.toggle('dark');$('#themeToggle').textContent=document.body.classList.contains('dark')?'☾':'☼';localStorage.setItem('royalstayTheme',document.body.classList.contains('dark')?'dark':'light')});if(localStorage.getItem('royalstayTheme')==='dark'){document.body.classList.add('dark');$('#themeToggle').textContent='☾'}
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.12});
$$('.reveal').forEach(el=>observer.observe(el));
$$('.thumbs button').forEach(btn=>btn.addEventListener('click',()=>{const img=btn.querySelector('img');$('.main-flat-img').src=img.src;$$('.thumbs button').forEach(b=>b.classList.remove('active'));btn.classList.add('active')}));
$$('.filter-bar button').forEach(btn=>btn.addEventListener('click',()=>{const filter=btn.dataset.filter;$$('.filter-bar button').forEach(b=>b.classList.remove('active'));btn.classList.add('active');$$('.gallery-item').forEach(item=>item.style.display=(filter==='all'||item.dataset.type===filter)?'block':'none')}));
const modal=$('#bookingModal');function openBooking(property=''){modal.classList.add('open');document.body.style.overflow='hidden';const user=JSON.parse(localStorage.getItem('royalstayUser')||'null');if(user)$('#bookName').value=user.name||'';if(property)$('#bookProperty').value=property}function closeBooking(){modal.classList.remove('open');document.body.style.overflow=''}
$$('[data-book]').forEach(btn=>btn.addEventListener('click',()=>openBooking(btn.dataset.book)));$('#closeModal').addEventListener('click',closeBooking);$('.modal-backdrop').addEventListener('click',closeBooking);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeBooking()});
$('#bookingForm').addEventListener('submit',e=>{e.preventDefault();$('#bookingForm').classList.add('hidden');$('#bookingSuccess').classList.remove('hidden')});$('#doneBooking').addEventListener('click',()=>{closeBooking();$('#bookingForm').reset();$('#bookingForm').classList.remove('hidden');$('#bookingSuccess').classList.add('hidden');showToast('Booking form cleared')});
function showToast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2800)}
const dot=$('.cursor-dot'),ring=$('.cursor-ring');window.addEventListener('mousemove',e=>{dot.style.left=e.clientX+'px';dot.style.top=e.clientY+'px';ring.animate({left:e.clientX+'px',top:e.clientY+'px'},{duration:180,fill:'forwards'})});$$('a,button').forEach(el=>{el.addEventListener('mouseenter',()=>{ring.style.width='46px';ring.style.height='46px';ring.style.background='rgba(201,164,92,.08)'});el.addEventListener('mouseleave',()=>{ring.style.width='32px';ring.style.height='32px';ring.style.background='transparent'})});
const today=new Date().toISOString().split('T')[0];$('#bookDate').min=today;
